//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingWeb.Controllers
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    /// <summary>
    /// The OperatorInterface class manages the presentation layer for the operator.
    /// </summary>
	public class OperatorController
	{
        /// <summary>
        /// Allows the operator to unlock the customers ID.
        /// </summary>
		public virtual void UnlockCustomerID()
		{
			throw new System.NotImplementedException();
		}

        /// <summary>
        /// Displays the status of the last request.
        /// </summary>
		private void DisplayStatus()
		{
			throw new System.NotImplementedException();
		}

        /// <summary>
        /// Displays the customers profile information.
        /// </summary>
		private void DisplayCustomerProfile()
		{
			throw new System.NotImplementedException();
		}

        /// <summary>
        /// Allows the operator to see the customer’s profile information.
        /// </summary>
		public virtual void RequestCustomerProfile()
		{
			throw new System.NotImplementedException();
		}

	}
}

