//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.BusinessProcess
{
    using OnlineBanking.DAL;
    using OnlineBanking.DataModel;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks; 

    /// <summary>
    /// Manages transactions for unlocking customers.
    /// </summary>
	public class UnlockIDManager
	{
 
        /// <summary>
        /// Unlock the customer profile in the data store. This is actually handled in the Account Controller.
        /// </summary>
        /// <returns></returns>
		public async virtual Task<bool> UnlockCustomerID(string customerEmail, string success)
		{
            try
            {
                Customer customer;
                using (var context = new BankContext())
                {
                    customer = await context.Customers.Where(c => c.email == customerEmail).FirstOrDefaultAsync<Customer>();

                    if (customer != null)
                    {
                        context.ProfileTransactions.Add(new ProfileTransaction()
                        {
                            CustomerID = customer.customerID,
                            status = success,
                            dateTime = DateTime.Now,
                            transactionType = Transaction.TransactionType.Statement
                        });
                    }
                    // if there is no customer, there is nothing to log the transaction against.
                    context.SaveChanges();
                }
                return true;
            }
            catch (Exception)
            {
                throw new Exception("Error unlocking the ID.");
            }
        }

	}
}

