//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// The data that defines an alert transaction
    /// </summary>
	public class AlertTransaction : Transaction
	{
          /// <summary>
        /// The account number for the alert.
        /// </summary>
        [MaxLength(25)]
        public string accountNumber
		{
			get;
			set;
		}

        /// <summary>
        /// The data that defines the alert, this is not yet specified.
        /// </summary>
        [MaxLength(255)]
        public String alertData
		{
			get;
			set;
		}

	}
}

