//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Represents an Alert on a bank account.
    /// </summary>
	public class Alert
	{
        /// <summary>
        /// The unique identifier for the alert.
        /// </summary>
        [Key]
        public int AlertID { get; set; }

        /// <summary>
        /// The account number to create the alert on.
        /// </summary>
        [MaxLength(25)]
        public string accountNumber
		{
			get;
			set;
		}

        /// <summary>
        /// The data that defines the alert, this is not yet specified.
        /// </summary>
        [MaxLength(255)]
        public String alertData
		{
			get;
			set;
		}

        /// <summary>
        /// Create an alert for an account
        /// </summary>
        /// <param name="alertData">The data that defines the alert, this is not yet specified.</param>
        /// <returns>the success status of the transaction</returns>
		public virtual bool SetUpAlerts(string alertData)
		{
			throw new System.NotImplementedException();
		}

	}
}

