//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Represents the bank.
    /// </summary>
	public class Bank
	{
        /// <summary>
        /// The name of the bank.
        /// </summary>
        [Key]
        [MaxLength(50)]
        public string bankName
		{
			get;
			set;
		}

        /// <summary>
        /// The address of the bank.
        /// </summary>
        [MaxLength(255)]
        public string bankAddress
		{
			get;
			set;
		}

        /// <summary>
        /// The list of customers for the bank.
        /// </summary>
		public virtual IEnumerable<Customer> Customer
		{
			get;
			set;
		}

        /// <summary>
        /// The list of transactions for the bank.
        /// </summary>
		public virtual IEnumerable<Transaction> Transaction
		{
			get;
			set;
		}

	}
}

