//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// The scanned image of the paper check.
    /// </summary>
	public class CheckImage
	{
        /// <summary>
        /// The unique identifier.
        /// </summary>
        [Key]
        public int checkImageID
        {
            get;
            set;
        }

        /// <summary>
        /// The account number that the check is drawn on.
        /// </summary>
        [MaxLength(25)]
        public string accountNumber
		{
			get;
			set;
		}

        /// <summary>
        /// The id of the related transaction
        /// </summary>
        public int transactionID
        {
            get;
            set;
        }

        /// <summary>
        /// The sequence number of the check.
        /// </summary>
        [MaxLength(25)]
        public string checkNumber
		{
			get;
			set;
		}

        /// <summary>
        /// The path to the actual image of the check.
        /// </summary>
		public string checkImage
		{
			get;
			set;
		}
	}
}

