//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// An instance of a checking account.
    /// </summary>
	public class CheckingAccount : Account
	{
        /// <summary>
        /// The amount of the last deposit.
        /// </summary>
		public Double lastDepositAmount
		{
			get;
			set;
		}

        /// <summary>
        /// The collection of checks that have been drawn on this account.
        /// </summary>
		public virtual IEnumerable<CheckImage> CheckImage
		{
			get;
			set;
		}

	}
}

