//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// The banks customer.
    /// </summary>
	public class Customer
	{
        /// <summary>
        /// The customer name.
        /// </summary>
        [MaxLength(50)]
        public string customerName
		{
			get;
			set;
		}

        /// <summary>
        /// The customers user ID.
        /// </summary>
        [Key]
        public int customerID
		{
			get;
			set;
		}

        /// <summary>
        /// The customers password (PIN).
        /// </summary>
        [MaxLength(50)]
        public string password
		{
			get;
			set;
		}

        /// <summary>
        /// The customers address.
        /// </summary>
        [MaxLength(255)]
        public string address
		{
			get;
			set;
		}

        /// <summary>
        /// the customers phone number.
        /// </summary>
        [MaxLength(25)]
        public string phone
		{
			get;
			set;
		}

        /// <summary>
        /// The customers email address.
        /// </summary>
        [MaxLength(50)]
        public string email
		{
			get;
			set;
		}

        /// <summary>
        /// The current status of the customers login (enabled/disabled)
        /// </summary>
        [MaxLength(1)]
        public string customerIdStatus
		{
			get;
			set;
		}

        /// <summary>
        /// The list of accounts that the customer owns.
        /// </summary>
		public virtual IEnumerable<Account> Accounts
		{
			get;
			set;
		}

        /// <summary>
        /// Validate the user ID and Password (PIN) that the customer entered.
        /// </summary>
        /// <param name="ID"></param>
        /// <param name="PIN"></param>
        /// <returns></returns>
		public virtual bool Validate(string ID, string PIN)
		{
			throw new System.NotImplementedException();
		}

        /// <summary>
        /// Read the customer profile from the data store.
        /// </summary>
        /// <returns></returns>
		public virtual Customer ReadCustomerProfile()
		{
			throw new System.NotImplementedException();
		}

        /// <summary>
        /// Update the customers profile to the data store.
        /// </summary>
        /// <param name="profileData"></param>
        /// <returns></returns>
		public virtual bool UpdateCustomerProfile(string profileData)
		{
			throw new System.NotImplementedException();
		}

        /// <summary>
        /// Unlock the customers user ID.
        /// </summary>
        /// <returns></returns>
		public virtual bool UnlockCustomerID()
		{
			throw new System.NotImplementedException();
		}

	}
}

