//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// An instance of a savings account.
    /// </summary>
	public class SavingsAccount : Account
	{
        /// <summary>
        /// The interest rate for the account.
        /// </summary>
		public Double Interest
		{
			get;
			set;
		}

	}
}

