//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Statement transaction data for logging.
    /// </summary>
	public class StatementTransaction : Transaction
	{
        /// <summary>
        /// The account number to that the statement was generated for. 
        /// </summary>
        [MaxLength(25)]
        public string accountNumber
		{
			get;
			set;
		}

        /// <summary>
        /// The month that the statement was generated for.
        /// </summary>
		public Double month
		{
			get;
			set;
		}

	}
}

