//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// An abstract transaction record for logging.
    /// </summary>
	public abstract class Transaction
	{

        public enum TransactionType
        {
            Alert=0, CheckImage=1, IDValidation=2, Profile=3, Query=4, Statement=5, Transfer=6, UnlockID=7
        }
        /// <summary>
        /// The ID of the transaction.
        /// </summary>
        [Key]
        public int transactionId
		{
			get;
			set;
		}

        /// <summary>
        /// the type of transaction.
        /// </summary>
        public TransactionType transactionType
		{
			get;
			set;
		}

        /// <summary>
        /// The customer ID.
        /// </summary>
        public int CustomerID
        {
            get;
            set;
        }

        /// <summary>
        /// The date and time of the transaction.
        /// </summary>
		public DateTime dateTime
		{
			get;
			set;
		}

        /// <summary>
        /// The status of the transaction (success or failure).
        /// </summary>
        public string status
		{
			get;
			set;
		}

 
        /// <summary>
        /// The account against which the transaction was applied.
        /// </summary>
		public virtual Account Account
		{
			get;
			set;
		}

	}
}

