//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.DataModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Transfer transaction data for logging.
    /// </summary>
	public class TransferTransaction : Transaction
	{
        /// <summary>
        /// The account number that the funds were transafered out of.
        /// </summary>
        [MaxLength(25)]
        public string fromAccountNumber
		{
			get;
			set;
		}

        /// <summary>
        /// The account number that the funds were transafered in to.
        /// </summary>
        [MaxLength(25)]
        public string toAccountNumber
		{
			get;
			set;
		}

        /// <summary>
        /// The ammount of the transaction.
        /// </summary>
        public double amount
        {
            get;
            set;
        }
    }
}

